---
title: "Analyse"
author: "JJayes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---


```{r}
library(tidyverse)
theme_set(theme_light())
df <- read_rds(here::here("data", "df_fathom.rds"))
```

## More Rstats or more Python?

```{r}
df %>%
  arrange(desc(created_at)) %>% 
  view
```

Most common hashtags?

```{r}
library(tidytext)

hashtags <- df %>%
  unnest(cols = c(hashtags)) %>%
  filter(!is.na(hashtags)) %>%
  mutate(hashtags = str_to_lower(hashtags)) %>%
  count(hashtags, is_retweet) %>%
  mutate(is_retweet = if_else(is_retweet == TRUE, 
                              "Retweet", 
                              "@fathomdata tweet"))
```


```{r}
library(ggsci)

hashtags %>% 
  group_by(is_retweet) %>% 
  slice_max(n, n = 12, with_ties = F) %>% 
  ungroup() %>% 
  mutate(language = str_detect(hashtags, "rstats|python|sql|css")) %>% 
  mutate(hashtags = reorder_within(hashtags, n, is_retweet)) %>% 
  ggplot(aes(n, hashtags, fill = n, colour = language)) +
  geom_col(show.legend = F) +
  scale_fill_material("blue") +
  scale_color_manual(values = c("white", "red")) +
  scale_y_reordered() +
  facet_wrap(~ is_retweet, scales = "free") +
  labs(x = "Number of tweets tagging")
```

```{r}
hashtags %>%
  filter(hashtags %in% c("rstats", "python", "sql", "css")) %>%
  mutate(hashtags = fct_reorder(hashtags, n)) %>%
  ggplot(aes(n, is_retweet, fill = hashtags)) +
  geom_col(position = "fill") +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(
    x = "Share of tweets tagging langauge",
    fill = "Language",
    y = NULL
  ) +
  scale_fill_npg(
    guide = guide_legend(reverse = TRUE)
  )
```

```{r}
hashtags %>%
  filter(hashtags %in% c("rstats", "python", "sql", "css")) %>%
  pivot_wider(names_from = is_retweet, values_from = n) %>%
  arrange(desc(`@fathomdata tweet`)) %>%
  knitr::kable()
```

Looking beyond just hashtags?

```{r}
df %>% select(text) %>% 
  mutate(rstats = str_detect(text, "rstats"),
         python = str_detect(text, "python")) %>% 
  summarise(across(c(rstats, python), sum))
```



Who does fathom retweet?

```{r}
df %>% 
  count(retweet_name, retweet_screen_name, sort = T) %>% 
  filter(!is.na(retweet_screen_name)) %>% 
  slice_max(n, n = 12, with_ties = F) %>% 
  knitr::kable()
```


```{r}
df <- read_rds(here::here("data", "df_fathom_datawookie.rds"))
```

```{r}
df %>% 
  count(screen_name)
```

```{r}
remove_bits <- "&amp;|&lt;|&gt;"

tidy_tweets <- df %>% 
  filter(!str_detect(text, "^RT")) %>%
  mutate(text = str_remove_all(text, remove_bits)) %>%
  unnest_tokens(word, text, token = "tweets") %>%
  filter(!word %in% stop_words$word,
         !word %in% str_remove_all(stop_words$word, "'"),
         str_detect(word, "[a-z]"))

frequency <- tidy_tweets %>% 
  group_by(screen_name) %>% 
  count(word, sort = TRUE) %>% 
  left_join(tidy_tweets %>% 
              group_by(screen_name) %>% 
              summarise(total = n())) %>%
  mutate(freq = n/total)

library(tidyr)

frequency <- frequency %>% 
  select(screen_name, word, freq) %>% 
  pivot_wider(names_from = screen_name, values_from = freq) %>%
  arrange(desc(datawookie, fathomdata))

```

```{r}
library(scales)

frequency %>% 
  ggplot(aes(datawookie, fathomdata)) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.25, height = 0.25) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = percent_format()) +
  scale_y_log10(labels = percent_format()) +
  geom_abline(color = "red") +
  theme(legend.position = "none")
```


```{r}
frequency %>% 
  mutate(highlight = word == "@standardbankza") %>% 
  ggplot(aes(datawookie, fathomdata)) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.25, height = 0.25) +
  geom_text(aes(label = word, colour = highlight), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = percent_format()) +
  scale_y_log10(labels = percent_format()) +
  geom_abline(color = "red") +
  scale_color_manual(values = c("grey80", "midnightblue")) +
  theme(legend.position = "none")
```

haha! 

```{r}
frequency %>% 
  filter(is.na(fathomdata)) %>% 
  select(-fathomdata) %>% 
  mutate(datawookie = scales::percent(datawookie)) %>% 
  slice_head(n = 10) %>% 
  knitr::kable()
```

